from os import getenv


TELEGRAM_API_ID = getenv('TELEGRAM_API_ID')
TELEGRAM_API_HASH = getenv('TELEGRAM_API_HASH')

TELEGRAM_FROM_CHAT_ID = getenv('TELEGRAM_FROM_CHAT_ID')
TELEGRAM_TO_CHAT_ID = getenv('TELEGRAM_TO_CHAT_ID')

SCHEDULER_DELAY_SECONDS = getenv('SCHEDULER_DELAY_HOURS')*3600
