from os import getenv


TELEGRAM_API_ID = getenv('TELEGRAM_API_ID')
TELEGRAM_API_HASH = getenv('TELEGRAM_API_HASH')
TELEGRAM_LOGIN_STRING = getenv('TELEGRAM_LOGIN_STRING')

TELEGRAM_FROM_CHAT_LINK = getenv('TELEGRAM_FROM_CHAT_LINK')
TELEGRAM_TO_CHAT_LINK = getenv('TELEGRAM_TO_CHAT_LINK')

SCHEDULER_DELAY_SECONDS = int(float(getenv('SCHEDULER_DELAY_HOURS'))*3600)
